name: mimeo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python 3.12
  - lastz
  - bedtools
  - trf
  - pip
  - pip:
      - biopython
      - pandas
      - hatch
      - pytest
      - pytest-cov
      - rich
