site_name: mimeo
site_description: Mimeo tools for alignment based repeat element annotation
site_author: adamtaranto
repo_name: adamtaranto/mimeo
repo_url: https://github.com/adamtaranto/mimeo
edit_uri: ""
use_directory_urls: true

nav:
  - Home: index.md
  - Getting Started: cli-tutorial.md


theme:
  name: material # material, readthedocs, mkdocs
  features:
    - navigation.top
    - navigation.expand
    # - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - attr_list
  - md_in_html

plugins:
  - search
  - mkdocs-jupyter:
      execute: False
  - mkdocstrings:
      handlers:
        python:
          # Reference: https://mkdocstrings.github.io/python/usage/
          options:
            # Heading options
            heading_level: 2
            show_root_full_path: False
            show_root_heading: True
            # Member options
            members_order: source # alphabetical, source
            # Docstrings options
            docstring_style: numpy
            docstring_section_style: spacy # table, list, spacy
            line_length: 89
            merge_init_into_class: True
            # Signatures/annotations options
            show_signature_annotations: True
            separate_signature: True
            # Additional options
            show_source: False
